#深度学习原理
概念知识：
    向量与标量概念：
    链式法则求导：
    激活函数：
    1.sigmoid
    2.tanh
    3.relu
    4.leaky relu
    5.softmax
    损失函数：
    1.MSE
    2.cross entropy
    梯度下降：
    反向传播：
    全连接层：
    神经网络的整体结构：输入层->若干隐藏层（全连接+激活）->输出层
    梯度下降三种变体：
        1.随机梯度下降:SGD
        2.批量梯度下降：BGD
        3.小批量梯度下降:Minibatch SGD
        --实践中最常用：Mini-batch SGD，批大小（Batch Size）通常取 32 / 64 / 128，多个批次组成一轮训练，遍历一次完整数据集 = 一个 Epoch
    训练流程总揽：前向传播->计算损失->反向传播->更新参数
    关键概念：epoch ,batch size

向量，标量

In [6]:
import numpy as np
#标量
temp = 2234
#向量
vec = np.array([1, 2, 3, 4, 5])
#矩阵
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(np.linalg.norm(vec))  # 计算向量的范数

a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))  # 矩阵乘法
print(np.multiply(a, b))  # 元素乘法

print("a.shape:", a.shape)
print(a[0, 1])  # 索引矩阵元素
print(a[:, 1])  # 索引矩阵列
print(a[1, :])  # 索引矩阵行
print("索引矩阵子块",a[0:2, 0:2])  # 索引矩阵子块
print(a.flatten())  # 将矩阵展平为一维数组

7.416198487095663
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
a.shape: (2, 2)
2
[2 4]
[3 4]
索引矩阵子块 [[1 2]
 [3 4]]
[1 2 3 4]
